### ISSUE TITLE
CPS-IoT Tutorial Tracking

### ISSUE THREAD

**Issue by tyler-potyondy** [tock/book#34]
# CPS-IoT Tutorial todos Tentative Outline

## 3/25 - 3/29
- [ ] RSSI (@tyler-potyondy)
- [ ] Channel Switching (@tyler-potyondy)
- [ ] EUI64 Getter (@tyler-potyondy)
- [ ] 6LoWPAN Capsule Panic Bug (@tyler-potyondy)
- [ ] Testing openthread-tock build system (Alex Vochescu, Gabriel Pavaloiu, @lschuermann)
  - Confirm current openthread_hello example app is able to build on your system
- [ ] Decide on application for tutorial 

## 4/1 - 4/5
- [ ] Border router setup
- [ ] Tutorial outline complete (@tyler-potyondy)
- [ ]  Testing:  (Alex Vochescu, Gabriel Pavaloiu, @lschuermann)
  - connect to network (and remain attached for up to 7 minutes) -- test this with checking child table on router cli (cmd `child table`)
  - receive UDP packets
- [ ] alarm wrapping at 7 minutes bug (@atar13 @samir-rashid)
- [ ] Write screen app (@bradjc?)
- [ ] brainstorm visualization?

## 4/8 - 4/12
- [ ] Complete docker setup work (@bradjc)
- [ ] Write openthread app and setup interprocess communication (@tyler)
- [ ] Test openthread  (Alex Vochescu, Gabriel Pavaloiu @lschuermann)
  - perform test with multiple routers and ~30 child nodes to test for any bugs that may arise from higher traffic etc (@tyler-potyondy)
- [ ] Write tutorial openthread section

## 4/15 - 4/19
- [ ] Write tutorial robustness section
- [ ] Setup border router scripting / additional
- [ ] Tutorial completed
- [ ] Pilot tutorial with Anthony and Samir

## 4/22 - 4/26
- [ ] Pilot / test tutorial with some group of undergrads unexposed to tock
_open for last minute or lingering issues_

## 4/29 - 5/3
_open for last minute or lingering issues_

## 5/6 - 5/10
- [ ] Send Setup Instructions to Participants

**Comment by bradjc** [comment]
What do we want the screen to do?
